using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DocPlus.Javascript {

    /// <summary>
    /// 表示一个变量的属性。
    /// </summary>
    public enum DocCommentAttribute {

        /// <summary>
        /// 这是根据解析结果动态生成的变量。
        /// </summary>
        AutoGeneratedMember = 0,

        /// <summary>
        /// 这是一个普通的有文档注释的变量。
        /// </summary>
        DocumentedMember = 1,

        /// <summary>
        /// 这是系统内置的变量。
        /// </summary>
        PredefinedMember = 2,

        /// <summary>
        /// 这是一个函数作用域变量。
        /// </summary>
        Scope = 3,

        ///// <summary>
        ///// 这是一个全局作用域变量。
        ///// </summary>
        //Global = 4

    }

}
